### ISSUE TITLE
今天发现歌曲评论打不开了，是不是网易云的接口又调整了？

### ISSUE THREAD

**Issue by nethuan** [Moriafly/DsoMusic#113]
歌曲评论打开，app闪退

**Comment by Moriafly** [comment]
更新 3.13.0 版本

**Comment by nethuan** [comment]
感谢大佬👍发送自我的盖乐世
-------- 原始信息 --------发件人： 不要糖醋放椒盐 ***@***.***> 日期: 2022/5/31  11:00  (GMT+08:00) 收件人： Moriafly/DsoMusic ***@***.***> 抄送： nethuan ***@***.***>, Author ***@***.***> 主题： Re: [Moriafly/DsoMusic] 今天发现歌曲评论打不开了，是不是网易云的接口又调整了？ (Issue #113) 

更新 3.13.0 版本
