### ISSUE TITLE
部分全面屏手机底栏尺寸异常

### ISSUE THREAD

**Issue by Misachu-rail** [Moriafly/DsoMusic#13]
在通过小米MIX2和一加8T使用Dos music时发现底部播放控制栏的尺寸异常偏高，其中要属MIX2最为严重，附图如下，第一张是MIX2，第二张是一加8T。
![16122335743973838896051864010805](https://user-images.githubusercontent.com/28702990/106544704-f48c1480-6542-11eb-982f-2252a6830a9b.jpg)
![1612233589348406272746682917414](https://user-images.githubusercontent.com/28702990/106544718-fce44f80-6542-11eb-9555-4de268b88a2c.jpg)

**Comment by Moriafly** [comment]
图片好像看不了（可能是我没科学上网）。
更新 2.6.1-beta 版本在设置中关闭【导航栏适配】看下还会出现问题吗？
播放界面也有反馈说偏高，已经修复，更新版本会在后续发布。
感谢反馈~

**Comment by Misachu-rail** [comment]
OK，关闭后重启应后就恢复正常了，多谢解答。

**Comment by Moriafly** [comment]
🥰
