### ISSUE TITLE
网易云灰色歌曲

### ISSUE THREAD

**Issue by carey036** [Moriafly/DsoMusic#15]
希望灰色歌曲（提示网易云暂无版权的音乐）可以匹配云盘，或者自动在酷我/QQ里面匹配音乐（不知难度是否很大）
感激作者的项目！

**Comment by Moriafly** [comment]
匹配云盘，可能会比较慢~我会去试试的！！！
酷我 / QQ 里面匹配音乐是可以实现的，不过准确性可能会有点问题，也会去尝试~
超级感谢反馈🥳

**Comment by Moriafly** [comment]
> 希望灰色歌曲（提示网易云暂无版权的音乐）可以匹配云盘，或者自动在酷我/QQ里面匹配音乐（不知难度是否很大）
> 感激作者的项目！
匹配云盘，可能会比较慢我会去试试的！！！
酷我 / QQ 里面匹配音乐是可以实现的，不过准确性可能会有点问题，也会去尝试
超级感谢反馈🥳

**Comment by xqXQzzz1** [comment]
https://github.com/nondanee/UnblockNeteaseMusic，可以参考这个
