### ISSUE TITLE
访问某些用户主页的时候会崩溃

### ISSUE THREAD

**Issue by 500InternalError** [Moriafly/DsoMusic#16]
![Screenshot_20210205-231723_Smart Manager](https://user-images.githubusercontent.com/39024699/107053430-c2f89f00-6809-11eb-8bf6-9a789303b20b.jpg)（崩太快了只能截个崩溃记录的屏）
崩溃时访问的用户名：不怕周树人
![SmartSelect_20210205-233027_Dso Music](https://user-images.githubusercontent.com/39024699/107053768-2edb0780-680a-11eb-8c71-1a941c1f52a7.jpg)
怀疑是不是这个用户头像或者主页背景体积太大溢出了

**Comment by Moriafly** [comment]
确实存在这个问题，上次测试是溢出，今天测试返回的背景图片链接为 null ，已经修复了这个问题~谢谢！
