### ISSUE TITLE
能否优化横屏模式

### ISSUE THREAD

**Issue by Evinemz** [Moriafly/DsoMusic#22]
你好，我很喜欢你做的这款播放器，想装在车机上替换默认的播放器，但现在有个问题，车机上是横屏模式，播放器为磁带界面，磁带控制按钮不太简明，白色底色稍显刺眼，不利于夜晚驾驶，恳请作者能否优化一下 横屏模式界面跟竖屏界面一致？谢谢

**Comment by Moriafly** [comment]
2.7.1 版本已完成横屏模式开发
