### ISSUE TITLE
登录失败，请检查用户名或密码

### ISSUE THREAD

**Issue by yukiryo** [Moriafly/DsoMusic#26]
![Screenshot_20210226-000836](https://user-images.githubusercontent.com/58250223/109181482-eb4f3a00-77c6-11eb-88e2-33663582a62b.jpg)
确定手机号和密码都是正确的

**Comment by Moriafly** [comment]
是的，这两天，都是返回错误代码 250 造成的这个原因，其他的第三方 API 也有这样的问题，已经向库作者反馈。
谢谢！元宵节快乐

**Comment by Moriafly** [comment]
已经修复
