### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by realyiu** [Moriafly/DsoMusic#30]
打开时就闪退...

设备情况：Exynos 7420处理器，运行Android 7.0

测试了一下只有v2.7.1版和以前的版本可以正常使用，试了“海上明月共潮生修复版”依然闪退，望修复！

**Comment by realyiu** [comment]
> 收到，暂未发现原因，我会去进行安卓 7.0 虚拟机测试，谢谢反馈

“江流宛转绕芳甸”这版还是闪退。。。

**Comment by Moriafly** [comment]
是否有运行 Xposed 相关框架？

**Comment by realyiu** [comment]
> 是否有运行 Xposed 相关框架？

有的

**Comment by realyiu** [comment]
> 是否有运行 Xposed 相关框架？

果然关闭xposed框架后可以进界面了。不能共存吗，有没有什么好的解决办法？

**Comment by Moriafly** [comment]
会在下个版本修复这个问题~

**Comment by Moriafly** [comment]
🥳

**Comment by Moriafly** [comment]
已经发布新版~

**Comment by realyiu** [comment]
> 已经发布新版~

谢谢

**Comment by realyiu** [comment]
> 已经发布新版~

3.0版本又开始闪退了，和xposed不兼容

**Comment by Moriafly** [comment]
收到~

**Comment by Moriafly** [comment]
3.1.0 修复
