### ISSUE TITLE
Accessibility 支持

### ISSUE THREAD

**Issue by cary-rowen** [Moriafly/DsoMusic#36]
## 描述

开发者您好！
我是一位视障用户，平时依靠屏幕阅读器使用电脑 / 手机，在 Android 端的屏幕阅读器是 Google 的辅助功能服务——[Talkback](https://play.google.com/store/apps/details?id=com.google.android.marvin.talkback&hl=en_US&gl=US)，该服务会将屏幕上的文字信息以 TTS 形式反馈给用户。
在 使用 Dso Music 过程中发现了几个 Accessibility 相关的障碍，主要表现为 Talkback 无法读出按钮的真实用途（如 播放 / 暂停、上/下一首等），而是只能朗读"未加标签的按钮"，这是因为在开发过程中没有为按钮添加相关的无障碍属性所致。

如果使用 ImageView、ImageButton、CheckBox 或其他以图形方式传达信息的 View，请使用 android:contentDescription 属性为该 View 提供内容标签。（**不需要加上元素类型或状态**）。
内容标签有时取决于仅在运行时呈现的信息；View 的含义也可能随时间不断变化。例如，在音乐播放期间时，播放按钮可能变为暂停按钮。在这种情况下，请使用 View#setContentDescription(CharSequence contentDescription) 适时更新内容标签。
对于 EditText 或可编辑的 TextView，请使用 android:hint 属性指明文本字段的用途。不能够将 android:contentDescription 用作可编辑 View 的内容标签。

在 Dso Music 中播放器控制区域的上一首、下一首、播放 / 暂停、播放列表，模式切换等按钮缺少文本标签； 右上角搜索按钮、搜索框旁边的清除输入按钮也缺少文本标签，希望作者能够优化。

## 一些可能有用的参考链接

1. [内容标签 - Android 无障碍功能帮助](https://support.google.com/accessibility/android/answer/7158690?hl=zh-Hans)
2. [盲人怎么用手机？如何打造视障友善的app？](https://zhuanlan.zhihu.com/p/169371267)
3. [Accessibility 开发文档](https://developer.android.com/guide/topics/ui/accessibility/)

**Comment by Moriafly** [comment]
你好，我是 Dso Music 开发者。刚刚起床就看到了这个反馈，并自己打开了 Talkback ，确实在 Talkback 下我的软件太难用了。
最近会对这方面就行优化，会包括添加对一些控制按钮的提示、增大一些按钮的可触发区域和更好的文本反馈。
谢谢你使用本软件。

**Comment by cary-rowen** [comment]
感谢开发者的迅速答复，如需相关测试可以随时联系我。
E-mail: manchen_0528@outlook.com
