### ISSUE TITLE
歌单无法正常拉取

### ISSUE THREAD

**Issue by Nyasachu** [Moriafly/DsoMusic#47]
不清楚是不是网易调整所致，还是我个人问题。刚刚发现网易云的歌单只能显示歌单中的第一首。
![Screenshot_20210331-235507](https://user-images.githubusercontent.com/28702990/113174020-8e8ae780-927c-11eb-8808-86ffc88a9261.jpg)

**Comment by youshiqinggg** [comment]
我的也出现了同样的问题

**Comment by Moriafly** [comment]
昨晚一个公众号未经允许分享了这个软件，接口炸了

**Comment by Moriafly** [comment]
已经修复
