### ISSUE TITLE
为什么图片缓存这么离谱，我是来听歌的啊

### ISSUE THREAD

**Issue by Raudience** [Moriafly/DsoMusic#49]

**Comment by Moriafly** [comment]
嗯，歌单加了图片显示，就是这么高，可以通过设置中清理。

**Comment by Moriafly** [comment]
后续会移除，暂时没好方法，希望理解。

**Comment by cheart8** [comment]
嗯嗯发自我的华为手机-------- 原始邮件 --------发件人： Moriafly ***@***.***>日期： 2021年4月2日周五 上午10:02收件人： Moriafly/DsoMusic ***@***.***>抄送： Raudience ***@***.***>, Author ***@***.***>主    题： Re: [Moriafly/DsoMusic] 为什么图片缓存这么离谱，我是来听歌的啊 (#49)

后续会移除，暂时没好方法，希望理解。

**Comment by cheart8** [comment]
还有就是我手机号无法登录，错误码250发自我的华为手机-------- 原始邮件 --------发件人： Moriafly ***@***.***>日期： 2021年4月2日周五 上午10:02收件人： Moriafly/DsoMusic ***@***.***>抄送： Raudience ***@***.***>, Author ***@***.***>主    题： Re: [Moriafly/DsoMusic] 为什么图片缓存这么离谱，我是来听歌的啊 (#49)

后续会移除，暂时没好方法，希望理解。

**Comment by Moriafly** [comment]
被恶意传播冲爆了，下个版本会移除手机号登录

**Comment by qianyigengwu** [comment]
能不能缓存更低分辨率的图片呢？比如48x48的，实际上在歌曲列表里也用不了多大的图片。

**Comment by mercutiojohn** [comment]
我记得可以通过在获取缩略图URL后面加param的方式得到低分辨率图像
