### ISSUE TITLE
那个网易云API怎么用，我是小白，完全不会，但是我也想用

### ISSUE THREAD

**Issue by cheart8** [Moriafly/DsoMusic#51]

**Comment by Moriafly** [comment]
启用服务后填入服务地址
可以用我的 https://cloudmusic.moriafly.xyz
只是开发版，不太稳定

**Comment by cheart8** [comment]
> 启用服务后填入服务地址
> 可以用我的 https://cloudmusic.moriafly.xyz
> 只是开发版，不太稳定
