### ISSUE TITLE
 博主你好，在LyricsBackgroundRunnable.java这个爆红。我也没有在文件里找到这个类，这是怎么回事呢。

### ISSUE THREAD

**Issue by hejunv** [Moriafly/DsoMusic#52]
[code=java]
import com.dirror.music.widget.lyricBackground.LyricsBackgroundView;
[/code]
博主你好，在LyricsBackgroundRunnable.java这个爆红。我也没有在文件里找到这个类，这是怎么回事呢。

**Comment by bufanx** [comment]
我也没有找到这个类

**Comment by Moriafly** [comment]
已经移除~
