### ISSUE TITLE
关于二维码登录

### ISSUE THREAD

**Issue by olbb** [Moriafly/DsoMusic#75]
- 相对账户/密码登录来说会要安全一些
- 交互比较蠢,只能用另一台装了网易云的手机扫码或者截图/保存二维码到相册后用网易云扫描从相册中选择
- 二维码显示后需要对服务器做轮询操作, 对服务器压力可能较大
- 基本已经开发完了,有必要同步过来的话就说下?

**Comment by Sostay** [comment]
支持支持~

**Comment by Moriafly** [comment]
支持支持大佬！

**Comment by olbb** [comment]
已提交PR #77
