### ISSUE TITLE
PC端有类似功能的客户端么？

### ISSUE THREAD

**Issue by Sostay** [Moriafly/DsoMusic#76]
求推荐…… 先谢了~

**Comment by Moriafly** [comment]
有个叫 YesMusicPlayer，还有 Listen1 等等，Github 搜搜就有~

**Comment by txyyh** [comment]
> 有个叫 YesMusicPlayer，还有 Listen1 等等，Github 搜搜就有~

那个叫 yesplaymusic 。。。。
