### ISSUE TITLE
自行编译签名安装，打开后白屏

### ISSUE THREAD

**Issue by shunf4** [Moriafly/DsoMusic#84]
采用 master 分支代码（https://github.com/Moriafly/DsoMusic/commit/3311644fdef690c1885dd3a57986a0e7c5215655 ），自行使用 Android Studio 4.2.1 的 Generate Signed Bundle or APK 功能，用自己的 Keystore 创建一个 V2 签名的 release 包，安装后白屏。

若是采取在 build.gradle 里写 `signingConfigs.release` 再直接构建 APK，问题依旧。

产物如下：

[app-release.zip](https://github.com/Moriafly/DsoMusic/files/7154873/app-release.zip)

但发现如果在 release 配置里添加 `debuggable true`，一切正常。

**Comment by Moriafly** [comment]
尝试移除 com/dirror/music/util/Secure.kt 中相关代码
