### ISSUE TITLE
本地音乐无法播放，提示“当前歌曲不可用，播放下一首”（含原因推测）

### ISSUE THREAD

**Issue by kqwyf** [Moriafly/DsoMusic#90]
首先感谢项目作者和贡献者为这个APP奉献的心血，感觉它解决了我的一大痛点，就是把不同来源（主要是网易云和本地）的歌曲储存在同一张歌单中。不过在播放本地音乐时我遇到了一点问题，如下。

设备：红米K30 5G，MIUI 12.5

现象：播放本地音乐时当前播放歌曲会快速在整个列表内循环遍历（整个列表中均为本地音乐），同时不停提示“当前歌曲不可用，播放下一首”。

经查该提示出自
https://github.com/Moriafly/DsoMusic/blob/5d8450b0a41326468d73d2bb46da35174f01dbb3/app/src/main/java/com/dirror/music/service/MusicService.kt#L413

据代码上下文查到，在ServiceSongUrl.kt中曾有如下一段
https://github.com/Moriafly/DsoMusic/blob/5c5f3f63f0c55d067bcdb55ed9dd28aab9cce620/app/src/main/java/com/dirror/music/service/ServiceSongUrl.kt#L34

但`SOURCE_LOCAL`这个case在 https://github.com/Moriafly/DsoMusic/commit/fbc42338d7cbbac447133577fba1ff35d611590c 这个commit中被删除了。由于我不太看得懂这些代码，不知道当初删除这一段的原因为何，不过推测或许是这一改动导致本地音乐无法正常播放。

实际上我也测试了Releases中3.11.1版本可以正常播放本地音乐，3.11.2(749)就不能播放了。查看了3.11.1对应分支的代码也发现`SOURCE_LOCAL`这一case是存在的。

以上只是个人对错误原因的一点推测，因为我其实并不会写Kotlin和安卓APP，只能连蒙带猜去看代码，希望尽可能为开发者减少一点工作量。谢谢！

**Comment by Moriafly** [comment]
十分感谢！！！

**Comment by Moriafly** [comment]
已经修复💕
