### ISSUE TITLE
网易云不能读取歌单  

### ISSUE THREAD

**Issue by qiangweijian** [Moriafly/DsoMusic#91]
自己的还有推荐歌单都能显示但是打开空白  云盘可以显示歌曲但是不能播放  MIUI12.5  安卓11  移动宽带  联通移动流量 都尝试过

**Comment by Moriafly** [comment]
感谢反馈

**Comment by olbb** [comment]
应该是API_NEW这个接口失效引起的, 有一部分接口是写死的, 晚些我改下,也可以使用自己配置的接口

**Comment by olbb** [comment]
已提交 #93

**Comment by Moriafly** [comment]
已经合并发布新版本 https://github.com/Moriafly/DsoMusic/releases/tag/3.11.4
