### ISSUE TITLE
网易云api无法使用

### ISSUE THREAD

**Issue by JingwenWang-Jingle** [Moriafly/DsoMusic#92]
![Screenshot_2021-11-17-00-51-50-440_com.dirror.music.jpg](https://user-images.githubusercontent.com/88672087/142029324-c3cc1df5-400a-478a-ba6d-01320d9dc8aa.jpg)![IMG_20211117_005318.jpg](https://user-images.githubusercontent.com/88672087/142029541-ad419ffc-6aa8-4518-9fab-4e6c95be3168.jpg)
![Screenshot_2021-11-17-00-57-35-409_com.dirror.music.jpg](https://user-images.githubusercontent.com/88672087/142030242-a0b7da70-c6e9-40b4-80fb-3f91ea5b0f02.jpg)
已经输入网易云api，且打开服务，仍然无法使用手机号登录，可以确定帐号密码没有错误。
在使用UID登陆以后，仍然无法搜索到网易云上的歌曲。

**Comment by JingwenWang-Jingle** [comment]
三个api都已经尝试，都无法使用😭😭😭

**Comment by Moriafly** [comment]
尝试去除链接最后的 /

**Comment by JingwenWang-Jingle** [comment]
> 默认搜索接口挂掉了, 搜索的时候也没用这个配置 
> 已经提交pr 修复 #93 
> 👌谢谢，麻烦了。软件超级好用♥️♥️♥️

**Comment by Moriafly** [comment]
已经合并发布新版本 https://github.com/Moriafly/DsoMusic/releases/tag/3.11.4

**Comment by JingwenWang-Jingle** [comment]
可以使用了❤️❤️❤️

**Comment by txyyh** [comment]
@Moriafly 部分问题依然存在
无论手机号还是扫码均无法正常登陆，已尝试作者两个接口和自建vercel接口(v4.2.0)
手机号登录报错如图所示
扫码界面正常显示二维码，但登录后显示“无法获取用户数据”
